name: Flatten Folder Structure for c++

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 실행

jobs:
  restructure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Move and rename files inside c++
        run: |
          mkdir temp_flattened
          
          # c++ 내부의 파일만 처리
          find c++ -type f -mindepth 2 | while read filepath; do
            foldername=$(basename $(dirname "$filepath"))  # 상위 폴더 이름 가져오기
            extension="${filepath##*.}"  # 파일 확장자
            filename="${foldername}.${extension}"  # 새로운 파일명

            # 중복된 파일명 처리
            count=1
            while [ -e "temp_flattened/$filename" ]; do
              filename="${foldername}_${count}.${extension}"
              ((count++))
            done

            mv "$filepath" "temp_flattened/$filename"
          done

          # 기존 c++ 내부 폴더 삭제 & 파일 이동
          rm -rf c++/*
          mv temp_flattened/* c++/
          rmdir temp_flattened

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Flatten folder structure inside c++" || echo "No changes to commit"
          git push origin main --force
